# Generated by Django 5.2.6 on 2025-09-24 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the user', max_length=255)),
                ('date_of_birth', models.DateField(help_text='Date of birth in YYYY-MM-DD format')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Gender of the user', max_length=20)),
                ('location', models.CharField(help_text="User's location", max_length=255)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Phone number with country code', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Basic Information',
                'verbose_name_plural': 'Basic Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
