# Generated by Django 5.2.6 on 2025-09-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('usda_food_id', models.CharField(blank=True, max_length=100, null=True)),
                ('calories_per_100g', models.FloatField(blank=True, null=True)),
                ('protein_per_100g', models.FloatField(blank=True, null=True)),
                ('carbs_per_100g', models.FloatField(blank=True, null=True)),
                ('fat_per_100g', models.FloatField(blank=True, null=True)),
                ('fiber_per_100g', models.FloatField(blank=True, null=True)),
                ('sugar_per_100g', models.FloatField(blank=True, null=True)),
                ('total_calories', models.FloatField(blank=True, null=True)),
                ('total_protein', models.FloatField(blank=True, null=True)),
                ('total_carbs', models.FloatField(blank=True, null=True)),
                ('total_fat', models.FloatField(blank=True, null=True)),
                ('total_fiber', models.FloatField(blank=True, null=True)),
                ('total_sugar', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
