# Generated by Django 5.2.6 on 2025-09-24 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0003_foodnutrition_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutritionGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories_goal', models.FloatField(default=2000.0, help_text='Daily calorie goal')),
                ('daily_protein_goal', models.FloatField(default=50.0, help_text='Daily protein goal in grams')),
                ('daily_carbs_goal', models.FloatField(default=250.0, help_text='Daily carbohydrates goal in grams')),
                ('daily_fat_goal', models.FloatField(default=65.0, help_text='Daily fat goal in grams')),
                ('daily_fiber_goal', models.FloatField(default=25.0, help_text='Daily fiber goal in grams')),
                ('daily_sugar_goal', models.FloatField(default=50.0, help_text='Daily sugar goal in grams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
