# Generated by Django 5.2.6 on 2025-09-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0004_basic_info_user_alter_usermetric_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermetric',
            name='user',
        ),
        migrations.DeleteModel(
            name='Basic_Info',
        ),
        migrations.DeleteModel(
            name='UserMetric',
        ),
    ]
