# Generated by Django 5.2.6 on 2025-09-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0004_usernutritiongoals'),
        ('nexusapp', '0008_userhealthprofile'),
    ]

    operations = [
    ]
