# Generated by Django 5.2.6 on 2025-09-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0009_merge_0004_usernutritiongoals_0008_userhealthprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodnutrition',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('oz', 'ounces'), ('lb', 'pounds'), ('cup', 'cups'), ('ml', 'milliliters'), ('l', 'liters')], default='g', max_length=10),
        ),
    ]
