# Generated by Django 5.2.6 on 2025-09-24 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0009_merge_0004_usernutritiongoals_0008_userhealthprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemoglobin', models.CharField(blank=True, help_text="Hemoglobin level (e.g., '13.5 g/dL')", max_length=50)),
                ('hematocrit', models.CharField(blank=True, help_text="Hematocrit percentage (e.g., '40%')", max_length=50)),
                ('wbc_count', models.CharField(blank=True, help_text="White Blood Cell count (e.g., '7.2 x10^3/µL')", max_length=50)),
                ('rbc_count', models.CharField(blank=True, help_text="Red Blood Cell count (e.g., '4.7 x10^6/µL')", max_length=50)),
                ('platelet_count', models.CharField(blank=True, help_text="Platelet count (e.g., '250 x10^3/µL')", max_length=50)),
                ('mcv', models.CharField(blank=True, help_text="Mean Corpuscular Volume (e.g., '90 fL')", max_length=50)),
                ('mch', models.CharField(blank=True, help_text="Mean Corpuscular Hemoglobin (e.g., '30 pg')", max_length=50)),
                ('mchc', models.CharField(blank=True, help_text="Mean Corpuscular Hemoglobin Concentration (e.g., '33 g/dL')", max_length=50)),
                ('neutrophils', models.CharField(blank=True, help_text="Neutrophils percentage (e.g., '60%')", max_length=50)),
                ('lymphocytes', models.CharField(blank=True, help_text="Lymphocytes percentage (e.g., '30%')", max_length=50)),
                ('monocytes', models.CharField(blank=True, help_text="Monocytes percentage (e.g., '6%')", max_length=50)),
                ('eosinophils', models.CharField(blank=True, help_text="Eosinophils percentage (e.g., '3%')", max_length=50)),
                ('basophils', models.CharField(blank=True, help_text="Basophils percentage (e.g., '1%')", max_length=50)),
                ('test_date', models.DateField(blank=True, help_text='Date when the blood test was conducted', null=True)),
                ('lab_name', models.CharField(blank=True, help_text='Name of the laboratory', max_length=255)),
                ('doctor_name', models.CharField(blank=True, help_text='Name of the ordering physician', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_test_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
