# Generated by Django 5.2.6 on 2025-09-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0010_add_unit_to_food_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthprofile',
            name='daily_calorie_goal',
            field=models.FloatField(default=2000.0, help_text='Daily calorie goal'),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='daily_protein_goal',
            field=models.FloatField(default=50.0, help_text='Daily protein goal in grams'),
        ),
    ]
