# Generated by Django 5.2.6 on 2025-09-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0010_create_blood_test_report'),
        ('nexusapp', '0012_create_blood_test_report'),
    ]

    operations = [
    ]
