# Generated by Django 5.2.6 on 2025-09-25 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0013_merge_20250925_0545'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabolicPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.CharField(blank=True, help_text="Glucose level (e.g., '95 mg/dL')", max_length=50)),
                ('calcium', models.CharField(blank=True, help_text="Calcium level (e.g., '9.4 mg/dL')", max_length=50)),
                ('sodium', models.CharField(blank=True, help_text="Sodium level (e.g., '140 mmol/L')", max_length=50)),
                ('potassium', models.CharField(blank=True, help_text="Potassium level (e.g., '4.2 mmol/L')", max_length=50)),
                ('chloride', models.CharField(blank=True, help_text="Chloride level (e.g., '102 mmol/L')", max_length=50)),
                ('carbon_dioxide', models.CharField(blank=True, help_text="Carbon Dioxide (CO2) level (e.g., '25 mmol/L')", max_length=50)),
                ('bun', models.CharField(blank=True, help_text="Blood Urea Nitrogen (BUN) level (e.g., '14 mg/dL')", max_length=50)),
                ('creatinine', models.CharField(blank=True, help_text="Creatinine level (e.g., '0.9 mg/dL')", max_length=50)),
                ('test_date', models.DateField(blank=True, help_text='Date when the metabolic panel was conducted', null=True)),
                ('lab_name', models.CharField(blank=True, help_text='Name of the laboratory', max_length=255)),
                ('doctor_name', models.CharField(blank=True, help_text='Name of the ordering physician', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metabolic_panel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
