# Generated by Django 5.2.6 on 2025-09-25 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0014_create_metabolic_panel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverFunctionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_protein', models.CharField(blank=True, help_text="Total Protein level (e.g., '7.0 g/dL')", max_length=50)),
                ('albumin', models.CharField(blank=True, help_text="Albumin level (e.g., '4.5 g/dL')", max_length=50)),
                ('globulin', models.CharField(blank=True, help_text="Globulin level (e.g., '2.5 g/dL')", max_length=50)),
                ('ag_ratio', models.CharField(blank=True, help_text="A/G Ratio (e.g., '1.8')", max_length=50)),
                ('total_bilirubin', models.CharField(blank=True, help_text="Total Bilirubin level (e.g., '0.8 mg/dL')", max_length=50)),
                ('direct_bilirubin', models.CharField(blank=True, help_text="Direct Bilirubin level (e.g., '0.2 mg/dL')", max_length=50)),
                ('indirect_bilirubin', models.CharField(blank=True, help_text="Indirect Bilirubin level (e.g., '0.6 mg/dL')", max_length=50)),
                ('ast_sgot', models.CharField(blank=True, help_text="AST (SGOT) level (e.g., '25 U/L')", max_length=50)),
                ('alt_sgpt', models.CharField(blank=True, help_text="ALT (SGPT) level (e.g., '30 U/L')", max_length=50)),
                ('alkaline_phosphatase', models.CharField(blank=True, help_text="Alkaline Phosphatase level (e.g., '90 U/L')", max_length=50)),
                ('ggt', models.CharField(blank=True, help_text="GGT level (e.g., '20 U/L')", max_length=50)),
                ('test_date', models.DateField(blank=True, help_text='Date when the liver function test was conducted', null=True)),
                ('lab_name', models.CharField(blank=True, help_text='Name of the laboratory', max_length=255)),
                ('doctor_name', models.CharField(blank=True, help_text='Name of the ordering physician', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liver_function_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
