# Generated by Django 5.2.6 on 2025-09-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0015_liverfunctiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodnutrition',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], help_text='Type of meal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foodnutrition',
            name='time',
            field=models.TimeField(blank=True, help_text='Time when food was consumed (HH:MM format)', null=True),
        ),
    ]
