# Generated by Django 5.2.6 on 2025-09-25 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0015_liverfunctiontest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, help_text='Name of the medicine', max_length=255)),
                ('frequency', models.CharField(blank=True, help_text="Frequency of medication (e.g., 'Twice daily', '3 times a day')", max_length=100)),
                ('medical_condition', models.CharField(blank=True, help_text='Medical condition for which the medication is prescribed', max_length=255)),
                ('no_of_pills', models.CharField(blank=True, help_text="Number of pills or dosage (e.g., '1 tablet', '2 capsules')", max_length=50)),
                ('next_order_date', models.DateField(blank=True, help_text='Next order date in YYYY-MM-DD format', null=True)),
                ('meds_reminder', models.CharField(blank=True, help_text='Reminder notes or instructions for medication', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
