# Generated by Django 5.2.6 on 2025-09-25 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0016_foodnutrition_meal_type_foodnutrition_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, help_text='Name of the medication', max_length=255)),
                ('frequency', models.CharField(blank=True, help_text="How often to take the medication (e.g., 'twice daily')", max_length=100)),
                ('medical_condition', models.CharField(blank=True, help_text='Medical condition being treated', max_length=255)),
                ('no_of_pills', models.IntegerField(blank=True, help_text='Number of pills per dose', null=True)),
                ('next_order_date', models.DateField(blank=True, help_text='Date when next order is needed', null=True)),
                ('meds_reminder', models.BooleanField(default=False, help_text='Enable medication reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
