# Generated by Django 5.2.6 on 2025-09-25 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0017_medicationdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(help_text='Date and time of the appointment')),
                ('location', models.CharField(help_text='Location/address of the appointment', max_length=255)),
                ('doctor_name', models.CharField(help_text='Name of the doctor', max_length=255)),
                ('doctor_specialization', models.CharField(help_text="Doctor's specialization (e.g., Cardiology, Dermatology)", max_length=255)),
                ('appointment_type', models.CharField(choices=[('general', 'General'), ('consultant', 'Consultant')], help_text='Type of appointment - General or Consultant', max_length=20)),
                ('reason', models.TextField(help_text='Reason for appointment (e.g., routine checkup, follow-up)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
    ]
