# Generated by Django 5.2.6 on 2025-09-25 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0018_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(help_text='Name/title of the lab report', max_length=255)),
                ('report_type', models.CharField(choices=[('blood_test', 'Blood Test'), ('urine_test', 'Urine Test'), ('x_ray', 'X-Ray'), ('mri', 'MRI Scan'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG/EKG'), ('pathology', 'Pathology Report'), ('other', 'Other')], help_text='Type of lab report', max_length=50)),
                ('lab_name', models.CharField(blank=True, help_text='Name of the laboratory', max_length=255)),
                ('doctor_name', models.CharField(blank=True, help_text='Name of the requesting doctor', max_length=255)),
                ('report_date', models.DateField(help_text='Date when the lab report was conducted')),
                ('report_file_base64', models.TextField(help_text='Lab report file stored as base64 string')),
                ('file_name', models.CharField(help_text='Original filename of the uploaded report', max_length=255)),
                ('file_type', models.CharField(help_text='File extension (e.g., pdf, jpg, png)', max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
